# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todoVer2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        # Delete Proj
        self.pushButton_DeleteProj = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DeleteProj.sizePolicy().hasHeightForWidth())
        self.pushButton_DeleteProj.setSizePolicy(sizePolicy)
        self.pushButton_DeleteProj.setMinimumSize(QtCore.QSize(96, 24))
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        self.pushButton_DeleteProj.setFont(font)
        self.pushButton_DeleteProj.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.pushButton_DeleteProj.setObjectName("pushButton_DeleteProj")
        self.gridLayout_2.addWidget(self.pushButton_DeleteProj, 1, 1, 1, 1)
        # Line Project
        self.lineEdit_LineProj = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_LineProj.sizePolicy().hasHeightForWidth())
        self.lineEdit_LineProj.setSizePolicy(sizePolicy)
        self.lineEdit_LineProj.setMinimumSize(QtCore.QSize(174, 54))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.lineEdit_LineProj.setFont(font)
        self.lineEdit_LineProj.setObjectName("lineEdit_LineProj")
        self.gridLayout_2.addWidget(self.lineEdit_LineProj, 0, 0, 2, 1)
        # Add Item
        self.pushButton_AddItem = QtWidgets.QPushButton(self.centralwidget, clickled= lambda: self.addItem())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddItem.sizePolicy().hasHeightForWidth())
        self.pushButton_AddItem.setSizePolicy(sizePolicy)
        self.pushButton_AddItem.setMinimumSize(QtCore.QSize(75, 24))
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        self.pushButton_AddItem.setFont(font)
        self.pushButton_AddItem.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.pushButton_AddItem.setObjectName("pushButton_AddItem")
        self.gridLayout_2.addWidget(self.pushButton_AddItem, 0, 3, 1, 1)
        # Delete Item
        self.pushButton_DeleteItem = QtWidgets.QPushButton(self.centralwidget, clickled= lambda: self.deleteItem())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DeleteItem.sizePolicy().hasHeightForWidth())
        self.pushButton_DeleteItem.setSizePolicy(sizePolicy)
        self.pushButton_DeleteItem.setMinimumSize(QtCore.QSize(75, 24))
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        self.pushButton_DeleteItem.setFont(font)
        self.pushButton_DeleteItem.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.pushButton_DeleteItem.setObjectName("pushButton_DeleteItem")
        self.gridLayout_2.addWidget(self.pushButton_DeleteItem, 1, 3, 1, 1)
        # Item List
        self.listWidget_ItemList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_ItemList.sizePolicy().hasHeightForWidth())
        self.listWidget_ItemList.setSizePolicy(sizePolicy)
        self.listWidget_ItemList.setMinimumSize(QtCore.QSize(600, 100))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.listWidget_ItemList.setFont(font)
        self.listWidget_ItemList.setObjectName("listWidget_ItemList")
        self.gridLayout_2.addWidget(self.listWidget_ItemList, 2, 2, 1, 2)
        # Line Item
        self.lineEdit_LineItem = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_LineItem.sizePolicy().hasHeightForWidth())
        self.lineEdit_LineItem.setSizePolicy(sizePolicy)
        self.lineEdit_LineItem.setMinimumSize(QtCore.QSize(525, 54))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.lineEdit_LineItem.setFont(font)
        self.lineEdit_LineItem.setObjectName("lineEdit_LineItem")
        self.gridLayout_2.addWidget(self.lineEdit_LineItem, 0, 2, 2, 1)
        # New Project
        self.pushButton_NewProj = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_NewProj.sizePolicy().hasHeightForWidth())
        self.pushButton_NewProj.setSizePolicy(sizePolicy)
        self.pushButton_NewProj.setMinimumSize(QtCore.QSize(96, 24))
        font = QtGui.QFont()
        font.setFamily("Fira Code SemiBold")
        font.setPointSize(10)
        self.pushButton_NewProj.setFont(font)
        self.pushButton_NewProj.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.pushButton_NewProj.setObjectName("pushButton_NewProj")
        self.gridLayout_2.addWidget(self.pushButton_NewProj, 0, 1, 1, 1)
        # Project List
        self.listWidget_ProjList = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_ProjList.setObjectName("listWidget_ProjList")
        self.gridLayout_2.addWidget(self.listWidget_ProjList, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # Save
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_DeleteProj.setText(_translate("MainWindow", "Delete Proj"))
        self.pushButton_AddItem.setText(_translate("MainWindow", "Add"))
        self.pushButton_DeleteItem.setText(_translate("MainWindow", "Delete"))
        self.pushButton_NewProj.setText(_translate("MainWindow", "New Proj"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

    def addItem(self):
        pass

    def deleteItem(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
